import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TrustChecker — Institutional Digital Trust",
  description: "Sovereign Risk Intelligence & Compliance Platform",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the nonce generated by proxy.ts
  const hdrs = await headers();
  const nonce = hdrs.get("x-nonce") || "";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Pass nonce to Next.js internal scripts */}
        <meta name="csp-nonce" content={nonce} />
      </head>
      <body className="min-h-full flex flex-col" nonce={nonce}>
        {children}
      </body>
    </html>
  );
}
