/**
 * Standardized Error Codes v1.0 (Phase 4)
 * All API errors should use these codes for consistency.
 */
module.exports = {
    // Auth
    AUTH_REQUIRED: 'AUTH_REQUIRED',
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
    AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',

    // Authorization
    FORBIDDEN: 'FORBIDDEN',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    ORG_MEMBERSHIP_REQUIRED: 'ORG_MEMBERSHIP_REQUIRED',

    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',
    MISSING_FIELD: 'MISSING_FIELD',

    // Resources
    NOT_FOUND: 'NOT_FOUND',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    CONFLICT: 'CONFLICT',

    // Rate limiting
    RATE_LIMITED: 'RATE_LIMITED',
    PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',

    // System
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    DATABASE_ERROR: 'DATABASE_ERROR',

    // Domain specific
    QR_NOT_FOUND: 'QR_NOT_FOUND',
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    SCAN_FRAUD_DETECTED: 'SCAN_FRAUD_DETECTED',
    TRUST_SCORE_LOW: 'TRUST_SCORE_LOW',
    WEBHOOK_LIMIT_EXCEEDED: 'WEBHOOK_LIMIT_EXCEEDED',
    ENGINE_UNAVAILABLE: 'ENGINE_UNAVAILABLE',
};
