/** Identity & Trust Layer — DID + Verifiable Credentials Dashboard */
import { State } from '../../core/state.js';
import { icon } from '../../core/icons.js';
let D = {};
async function load() {
    const h = { 'Authorization': 'Bearer ' + State.token };
    const [dids, vcs, types] = await Promise.all([
        fetch('/api/identity/did/registry', { headers: h }).then(r => r.json()).catch(() => ({})),
        fetch('/api/identity/vc/registry', { headers: h }).then(r => r.json()).catch(() => ({})),
        fetch('/api/identity/types', { headers: h }).then(r => r.json()).catch(() => ({}))
    ]);
    D = { dids, vcs, types };
}
export function render() {
    load(); return `
<div class="sa-page">
    <div class="sa-page-title"><h1>${icon('fingerprint')} Identity & Trust Layer</h1><p style="color:#94a3b8;margin:4px 0 16px">Decentralized Identity (DID) + Verifiable Credentials (VC) — W3C Standard</p>
        <div style="display:flex;gap:8px"><button onclick="window.idShowDID()" style="padding:8px 16px;background:#3b82f6;color:#fff;border:none;border-radius:8px;cursor:pointer;font-weight:600">${icon('plus')} Create DID</button><button onclick="window.idShowVC()" style="padding:8px 16px;background:#8b5cf6;color:#fff;border:none;border-radius:8px;cursor:pointer;font-weight:600">${icon('shield')} Issue VC</button></div></div>
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:20px">
        ${[{ l: 'DIDs Registered', v: D.dids?.total || 0, c: '#3b82f6', i: '🆔' }, { l: 'Active VCs', v: D.vcs?.total || 0, c: '#8b5cf6', i: '📜' }, { l: 'Entity Types', v: D.types?.entity_types?.length || 8, c: '#10b981', i: '📦' }, { l: 'VC Types', v: Object.keys(D.types?.vc_types || {}).length || 10, c: '#f59e0b', i: '🏅' }].map(k => `<div class="sa-card" style="text-align:center;padding:14px"><div style="font-size:20px">${k.i}</div><div style="font-size:22px;font-weight:700;color:${k.c}">${k.v}</div><div style="color:#94a3b8;font-size:0.72rem">${k.l}</div></div>`).join('')}
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:20px">
        <div class="sa-card"><h3 style="margin:0 0 10px;color:#f1f5f9">${icon('fingerprint')} DID Registry</h3>
            ${D.dids?.dids?.length > 0 ? `<table style="width:100%;border-collapse:collapse;font-size:0.78rem"><thead><tr style="border-bottom:2px solid #1e293b;color:#94a3b8;font-size:0.68rem;text-transform:uppercase"><th style="padding:4px;text-align:left">DID</th><th style="padding:4px">Type</th><th style="padding:4px">Status</th></tr></thead><tbody>${D.dids.dids.map(d => `<tr style="border-bottom:1px solid #1e293b"><td style="padding:4px;color:#3b82f6;font-family:monospace;font-size:0.68rem">${d.did}</td><td style="padding:4px;text-align:center;color:#94a3b8">${d.entity_type}</td><td style="padding:4px;text-align:center"><span style="padding:1px 6px;border-radius:4px;background:#10b98122;color:#10b981;font-size:0.68rem">${d.status}</span></td></tr>`).join('')}</tbody></table>` : '<div style="text-align:center;padding:20px;color:#64748b">No DIDs yet — Create one above</div>'}
        </div>
        <div class="sa-card"><h3 style="margin:0 0 10px;color:#f1f5f9">${icon('shield')} Verifiable Credentials</h3>
            ${D.vcs?.credentials?.length > 0 ? `<table style="width:100%;border-collapse:collapse;font-size:0.78rem"><thead><tr style="border-bottom:2px solid #1e293b;color:#94a3b8;font-size:0.68rem;text-transform:uppercase"><th style="padding:4px;text-align:left">VC ID</th><th style="padding:4px">Type</th><th style="padding:4px">Status</th></tr></thead><tbody>${D.vcs.credentials.map(v => `<tr style="border-bottom:1px solid #1e293b"><td style="padding:4px;color:#8b5cf6;font-family:monospace;font-size:0.68rem">${(v.vc_id || '').slice(0, 24)}</td><td style="padding:4px;text-align:center;color:#94a3b8;font-size:0.72rem">${v.credential_type}</td><td style="padding:4px;text-align:center"><span style="padding:1px 6px;border-radius:4px;background:${v.status === 'active' ? '#10b98122' : '#ef444422'};color:${v.status === 'active' ? '#10b981' : '#ef4444'};font-size:0.68rem">${v.status}</span></td></tr>`).join('')}</tbody></table>` : '<div style="text-align:center;padding:20px;color:#64748b">No VCs issued yet</div>'}
        </div>
    </div>
    <div class="sa-card"><h3 style="margin:0 0 10px;color:#f1f5f9">${icon('target')} Available VC Types</h3>
        <div style="display:grid;grid-template-columns:repeat(5,1fr);gap:6px">${Object.entries(D.types?.vc_types || {}).map(([k, v]) => `<div style="padding:8px;background:#0f172a;border-radius:6px;text-align:center"><div style="color:#f1f5f9;font-weight:600;font-size:0.72rem">${k.replace(/_/g, ' ')}</div><div style="color:#64748b;font-size:0.68rem">${v?.category || ''} · ${v?.validity_days || 0}d</div></div>`).join('')}</div>
    </div>
    <div id="id-modal" style="display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.6);z-index:1000;align-items:center;justify-content:center"><div style="background:#1e293b;border-radius:16px;padding:24px;width:420px;border:1px solid #334155"><h3 style="margin:0 0 16px;color:#f1f5f9">Create DID</h3><select id="id-type" style="width:100%;padding:8px;background:#0f172a;color:#f1f5f9;border:1px solid #334155;border-radius:6px;margin-bottom:8px">${['product', 'partner', 'factory', 'shipment', 'device', 'company', 'carrier', 'warehouse'].map(t => `<option>${t}</option>`).join('')}</select><input id="id-eid" placeholder="Entity ID" style="width:100%;padding:8px;background:#0f172a;color:#f1f5f9;border:1px solid #334155;border-radius:6px;margin-bottom:10px"><div id="id-res" style="display:none;padding:10px;background:#0f172a;border-radius:6px;margin-bottom:10px;font-size:0.78rem;color:#94a3b8"></div><div style="display:flex;gap:8px"><button onclick="window.idCreateDID()" style="flex:1;padding:10px;background:#3b82f6;color:#fff;border:none;border-radius:8px;cursor:pointer;font-weight:600">Generate DID</button><button onclick="document.getElementById('id-modal').style.display='none'" style="padding:10px 16px;background:#334155;color:#f1f5f9;border:none;border-radius:8px;cursor:pointer">Close</button></div></div></div>
    <div id="vc-modal" style="display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.6);z-index:1000;align-items:center;justify-content:center"><div style="background:#1e293b;border-radius:16px;padding:24px;width:420px;border:1px solid #334155"><h3 style="margin:0 0 16px;color:#f1f5f9">Issue Verifiable Credential</h3><input id="vc-issuer" placeholder="Issuer DID" style="width:100%;padding:8px;background:#0f172a;color:#f1f5f9;border:1px solid #334155;border-radius:6px;margin-bottom:8px"><input id="vc-subject" placeholder="Subject DID" style="width:100%;padding:8px;background:#0f172a;color:#f1f5f9;border:1px solid #334155;border-radius:6px;margin-bottom:8px"><select id="vc-type" style="width:100%;padding:8px;background:#0f172a;color:#f1f5f9;border:1px solid #334155;border-radius:6px;margin-bottom:10px">${Object.keys(D.types?.vc_types || { ISO_14001: 1, ESG_GRADE: 1, LOW_CARBON: 1, TRUST_VERIFIED: 1 }).map(t => `<option value="${t}">${t.replace(/_/g, ' ')}</option>`).join('')}</select><div id="vc-res" style="display:none;padding:10px;background:#0f172a;border-radius:6px;margin-bottom:10px;font-size:0.78rem;color:#94a3b8"></div><div style="display:flex;gap:8px"><button onclick="window.idIssueVC()" style="flex:1;padding:10px;background:#8b5cf6;color:#fff;border:none;border-radius:8px;cursor:pointer;font-weight:600">Issue VC</button><button onclick="document.getElementById('vc-modal').style.display='none'" style="padding:10px 16px;background:#334155;color:#f1f5f9;border:none;border-radius:8px;cursor:pointer">Close</button></div></div></div>
</div>`;
}
export function renderPage() { return render(); }
window.idShowDID = () => { document.getElementById('id-modal').style.display = 'flex'; };
window.idShowVC = () => { document.getElementById('vc-modal').style.display = 'flex'; };
window.idCreateDID = async () => { const h = { 'Authorization': 'Bearer ' + State.token, 'Content-Type': 'application/json' }; const r = await fetch('/api/identity/did', { method: 'POST', headers: h, body: JSON.stringify({ entity_type: document.getElementById('id-type').value, entity_id: document.getElementById('id-eid').value || 'E-' + Date.now() }) }).then(r => r.json()); document.getElementById('id-res').style.display = 'block'; document.getElementById('id-res').innerHTML = r.did ? `<div style="color:#10b981;font-weight:700"><span class="status-icon status-pass" aria-label="Pass"><span class="status-icon status-pass" aria-label="Pass">✓</span></span> ${r.did}</div>` : `<div style="color:#ef4444">${r.error || 'Failed'}</div>`; };
window.idIssueVC = async () => { const h = { 'Authorization': 'Bearer ' + State.token, 'Content-Type': 'application/json' }; const r = await fetch('/api/identity/vc/issue', { method: 'POST', headers: h, body: JSON.stringify({ issuer_did: document.getElementById('vc-issuer').value, subject_did: document.getElementById('vc-subject').value, credential_type: document.getElementById('vc-type').value }) }).then(r => r.json()); document.getElementById('vc-res').style.display = 'block'; document.getElementById('vc-res').innerHTML = r.vc_id ? `<div style="color:#10b981;font-weight:700"><span class="status-icon status-pass" aria-label="Pass"><span class="status-icon status-pass" aria-label="Pass">✓</span></span> ${r.vc_id}</div>` : `<div style="color:#ef4444">${r.error || 'Failed'}</div>`; };
